#!/usr/bin/env bash
# Bash Script must be 5 lines long/less & Cannot use ; && wget.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"